base_url = "https://pocly.jp"
title = "My Site"
output_dir = "docs"
theme = "goyo"
compile_sass = false
build_search_index = true

[markdown]
highlight_code = true

[extra]
nav = [
    {name = "Home", url = "/", type = "url" },
    {name = "Blog", url = "/blog", type = "url" },
    {name = "Products", url = "/pd", type = "url" },
]

